version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: masher88/kittygram_backend:0.2
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media_files/
  frontend:
    env_file: .env
    image: masher88/kittygram_frontend:0.2
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: masher88/kittygram_new_gateway:0.1
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media_files/
