#!/bin/bash

python manage.py migrate
echo "Migrations succeed"
python manage.py collectstatic
echo "Collectstatic succeed"
cp -r /app/collected_static/. /backend_static/static/
echo "Copy static succeed"
exec gunicorn --bind 0.0.0.0:9000 kittygram_backend.wsgi
echo "Gunicorn is running"
