name: Tags workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

job:

  build_backend_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Extract Git SHA
        run: |
          echo ${{ github.sha }}

